### ISSUE TITLE
Add a asset url prefix

### ISSUE THREAD

**Issue by CodingJinxx** [NiklasEi/bevy_asset_loader#102]
Adding a Optional Prefix to asset urls allows easier integration for Bevy WASM into existing Webtechnologies. For example in my case i had to prefix my asset path with _content because blazors routing ended up placing my assets at that url. Adding a simple method to the builder would allow me to do this 
```rust
            LoadingState::new(GameState::Loading)
                .withPrefix("_content/BlazoredBevy.UI/assets")
                .with_collection::<FontAssets>()
                .with_collection::<AudioAssets>()
                .with_collection::<TextureAssets>()
                .continue_to_state(GameState::Menu)
```

instead of: 
```rust
#[derive(AssetCollection, Resource)]
pub struct FontAssets {
    #[asset(path = "_content/BlazoredBevy.UI/assets/fonts/FiraSans-Bold.ttf")]
    pub fira_sans: Handle<Font>,
}
```

**Comment by NiklasEi** [comment]
This would be much nicer solved by setting the `asset_folder` as part of the `AssetPlugin` to be `_content/BlazoredBevy.UI/assets`. Have you tried that?

**Comment by NiklasEi** [comment]
I close this for now.
If the proposed solution doesn't work or you see any other reason why this requires changes in `bevy_asset_loader`, feel free to comment and reopen the issue 🙂
