### ISSUE TITLE
Mapped collections must be indexed using backslashes when running on Windows

### ISSUE THREAD

**Issue by elijaharita** [NiklasEi/bevy_asset_loader#135]
For example, I have an asset at `part_types/test_cube.ron`, and I can index it as such on Linux. But on Windows the resource gets inserted to the asset map with the key `part_types\\test_cube.ron`.

I think the path strings should be normalized to use slashes, or possibly the map could be indexed by a path type instead of a string.

**Comment by NiklasEi** [comment]
Yeah, those keys should be the same on different OS. I think strings with simple slashes would be the nicer solution. That also mimics the behavior of Bevy assets.
