### ISSUE TITLE
Dynamic asset paths?

### ISSUE THREAD

**Issue by johanhelsing** [NiklasEi/bevy_asset_loader#14]
I want to use bevy_asset_loader, but I have a few assets paths that are not known at compile time. (they're currently passed as command line arguments, but could be from config file etc.)

Maybe there could be some way of setting the asset paths dynamically?

I tried implementing the AssetCollection trait manually, but the method that starts loading is:

```
fn load(asset_server: &Res<AssetServer>) -> Vec<HandleUntyped>
```

So there is no reference to either world or self, which means I don't think it's possible to get the kind of state I want (which is in a bevy resource)?

**Comment by NiklasEi** [comment]
I think this is a very common issue and I would like to support it. My current plan is to introduce support for a key - value mapping that can be provided to the loader. You can then use a key as asset path and provide and value in the mapping (command line/ config file etc.). Does that sound good?

The load function taking only the asset_server is a good point. I already had to change the create function to take world and get called from an exclusive system. I think the same should happen for the load function.

**Comment by NiklasEi** [comment]
It is now possible to change the file path of an asset dynamically (see the new example). I will try extending this to make other asset options like texture atlas settings dynamic, too.

If anyone has any feedback about the feature and its API, please tell me. I am sure we can improve on the current implementation.
