### ISSUE TITLE
Loading `TextureAtlas` without attribute throws silent error 

### ISSUE THREAD

**Issue by 100-TomatoJuice** [NiklasEi/bevy_asset_loader#145]
When trying to load a `TextureAtlas` without a `texture_atlas` attribute, like
```rust
#[asset(path = "atlas.png")]
pub texture_atlas: Handle<TextureAtlas>
```
the loader says that the asset is loaded even though attempting to use the `Handle` causes nothing to render.

**Comment by NiklasEi** [comment]
As far as I can see there is not much we can do about this at the moment. Getting a handle from a string path will not carry the asset type information, so Bevy cannot know that we are asking for the wrong asset type.

Maybe this will change with Assets v2, but for now I will close this.
