### ISSUE TITLE
Deadlock when loading many GLTF models

### ISSUE THREAD

**Issue by dag-h** [NiklasEi/bevy_asset_loader#152]
`bevy_asset_loader` sometimes does not proceed out of the defined loading state when loading many (around 8+) GLTF models in an `AssetCollection`. Using [this minimal example](https://gitlab.com/dag-h/bevy_asset_loader_bug/) (models included in repo), the application fails to get out of the loading state about 2/10 times, and seems completely deadlocked. Reducing the number of models reduces the issue significantly.

I can reproduce the issue on several machines.

**Comment by NiklasEi** [comment]
Before I invest time into investigating this, I would like to see if this issue still persists after updating to Bevy 0.12. It might be fixed due to the significant changes in `bevy_assets`.

**Comment by NiklasEi** [comment]
@dag-h could you please test if your project can still deadlock with Bevy 0.12.1?

**Comment by NiklasEi** [comment]
I was able to reproduce the issue in roughly half of the runs with your repository. After updating to Bevy `0.12.1` and bevy_asset_loader `0.18.0`, the issue was resolved.
