### ISSUE TITLE
How to get Asset from a given Handle

### ISSUE THREAD

**Issue by PraxTube** [NiklasEi/bevy_asset_loader#154]
I am trying to get the asset data that is behind a handle, but I can't figure out how to achieve that. The [`Assets::get()`](https://docs.rs/bevy/latest/bevy/asset/struct.Assets.html#method.get) function is what you would typically use, but that doesn't work too nicely with the `AssetLoader`, at least I don't see how.

Any ideas how to get the Asset from a Handle?

**Comment by NiklasEi** [comment]
> but that doesn't work too nicely with the AssetLoader,

Are you writing an asset loader or what is your use case?

**Comment by PraxTube** [comment]
What I wanted to do was essentially [this](https://github.com/NiklasEi/bevy_asset_loader/blob/a60227c3b399f8ff49b94f5c26f69623fa3d4f29/bevy_asset_loader/examples/atlas_from_grid.rs#L41C43-L41C43), getting the Assed data that is behind a Handle. Which is exactly what I tried but somehow I thought it didn't work for whatever reason. Sorry for wasting your time, and thank you for trying to help :+1:
