### ISSUE TITLE
Asset path platform indipendence

### ISSUE THREAD

**Issue by fischi20** [NiklasEi/bevy_asset_loader#157]
Just a small quality of life change that would be nice. When giving a path for an asset with the derive macro (AssetCollection), the path doesn't get adapted to the platform, which means that a normal "path/to/asset" would not work if you are coding for windows, meanwhile if you are coding for every single other platform,  "path\\to\\asset" wouldn't work.

**Comment by NiklasEi** [comment]
Have you run into an issue concerning this? Bevy should handle the platform specific paths and should be fine with always getting paths like `path/to/asset`.

**Comment by fischi20** [comment]
That makes sense since I used the AssetServer it was actually fine. It might also just be that I messed something up with all the tampering with the OS, or some incorrectly configured cache, cause it's working as intended right now as well, sorry for the pointless issue if a restart and a night rest fixed it apparently.
