### ISSUE TITLE
Sampling not respected for dynamically loaded TextureAtlas?

### ISSUE THREAD

**Issue by feelingsonice** [NiklasEi/bevy_asset_loader#169]
I have my dynamic asset loaded like this:

```
({
    "image.tiles": TextureAtlas (
        path: "images/lab/tiles.png",
        sampler: Nearest,
        tile_size_x: 32.,
        tile_size_y: 48.,
        columns: 8,
        rows: 6,
    ),
})
```

But I don't think the sampler config "Nearest" is respected b/c the images still turns out blurry?

**Comment by NiklasEi** [comment]
Yes, this is a missing feature. At the moment the sampler field is only supported for `Image`, not for `TextureAtlas`.

**Comment by NiklasEi** [comment]
What I would also see as part of fixing this issue: a warning about unknown/ignored fields in dynamic assets.
