### ISSUE TITLE
[Feature Request] Asset preprocessing

### ISSUE THREAD

**Issue by feelingsonice** [NiklasEi/bevy_asset_loader#187]
Since v0.12 Bevy has added supported for [asset preprocessing](https://bevyengine.org/news/bevy-0-12/#enabling-pre-processing). I would love this integrated with `bevy_asset_loader`. Right now I'm loading a bunch of `.aseprite` files, processing the files into `Image` then `TextureAtlas`, this means I'm manually adding an additional state after the initial asset loading state to process the given `.aseprite` files, but it would be wonderful if I could, instead, simply abstract away the preprocessing into the asset loading state of `bevy_asset_loader`, somehow...

**Comment by NiklasEi** [comment]
Bevy's current preprocessing can convert assets and saves processed asset files. This is separate from what this plugin tries to do and can happen before packaging your game. You could try to preprocess your `.aseprite` files to images, then directly load the images as texture atlases with `bevy_asset_loader`.
To some extend you can also already move processing into a loading state using `init_resource`.

I see where your request comes from and agree that Bevy needs more features in that direction. But I would like to see these things in Bevy itself or in a separate third party crate.
