### ISSUE TITLE
Default dynamic asset collection extension to .ron

### ISSUE THREAD

**Issue by SpecificProtagonist** [NiklasEi/bevy_asset_loader#188]
(blocked on the update to Bevy 0.13)

In Bevy 0.13, asset loaders are differentiated primarily by asset type, not file extension, so the `.assets.ron` isn't needed anymore and can become just `.ron`.

**Comment by NiklasEi** [comment]
I know of the change, but I would have stuck with `.assets.ron` to differentiate the files from other `ron` files. Why would you prefer the ambiguous file ending?

**Comment by NiklasEi** [comment]
I will close this since the file ending is configurable on a loading state using `set_standard_dynamic_asset_collection_file_endings` and I think it is still helpful to have a unique file ending by default.

If you have arguments against this, feel free to re-open the issue and we can discuss it.
