### ISSUE TITLE
Nasty bug: Trying to load the same collection twice causes a freeze and no errors reported 

### ISSUE THREAD

**Issue by ethereumdegen** [NiklasEi/bevy_asset_loader#192]
Nasty bug: Trying to load the same collection twice causes a freeze and no errors reported 
Version: 0.19 

For example, do this in the foxtrot example: 
...

 .add_loading_state(
            LoadingState::new(AppState::Loading)
                .continue_to_state(AppState::PostLoading)
                .load_collection:: < AudioAssets >()  
                  .load_collection:: < AudioAssets >()  //this is duplicated and this causes the problem 
              ....
              
              
              
      Suggestion:  Make this error case throw an error

**Comment by NiklasEi** [comment]
I can reproduce this and will fix it, thank you for raising the issue.
