### ISSUE TITLE
MacOS collecting HashMap from a Folder fails

### ISSUE THREAD

**Issue by Aultus-defora** [NiklasEi/bevy_asset_loader#205]
`Failed to load folder. Could not find an asset loader matching: Loader Name: None; Asset Type: None; Extension: None; Path: Some("ability_images/.DS_Store");`
I am trying to just load images from the folder in question. How can I tell it to ignore `.DS_Store `file? Or ignore any non image file for that matter. This is pitfall of MacOS: it generates `.DS_Store` files all over the place

**Comment by NiklasEi** [comment]
There is no filter for only loading files from a directory with certain extensions yet (see bevyengine/bevy#2291). Your specific issue might get resolved if something like bevyengine/bevy#11214 gets merged.

**Comment by NiklasEi** [comment]
I will close this since there is nothing to be done in this plugin. You can join the relevant Bevy issues or open a new one if none fits.
