### ISSUE TITLE
bevy_asset_loader not working without the multi-threaded feature but shows no errors or warnings

### ISSUE THREAD

**Issue by AntonZelenin** [NiklasEi/bevy_asset_loader#206]
If the "multi-threaded" feature is not enabled, the project will work, but sprites that are loaded using bevy_asset_loader will not be rendered. Additionally, you won't be able to render them using AssetServer as well. But there are no warnings or errors and I didn't find any mention of it in docs or issues.
This issue is very unobvious and was hard to debug, so I think it would be nice to have some warning about it.

Here's a minimal example to reproduce
https://github.com/AntonZelenin/test_asset

If you run it, the screen will be empty. If you uncomment the line ` texture: asset_server.load("torch.png"),` it won't work as well. If you go to Cargo.toml and uncomment the "multi-threaded" feature, both variants will work fine.

Btw, I'm using Windows 10 if that matters.

**Comment by NiklasEi** [comment]
Thank you for raising this! I could reproduce the issue without bevy_asset_laoder and opened bevyengine/bevy#12951 for it.

**Comment by NiklasEi** [comment]
This is no longer broken in Bevy 0.15 :partying_face:
