### ISSUE TITLE
load_untyped vs Custom AssetLoaders

### ISSUE THREAD

**Issue by ChristopherBiscardi** [NiklasEi/bevy_asset_loader#207]
The usage of [load_untyped](https://github.com/NiklasEi/bevy_asset_loader/blob/fce89e2fdacecc09ed1e6b2bb3bdf2f9ba13fe00/bevy_asset_loader_derive/src/assets.rs#L440) seems to prevent the usage of otherwise valid custom assets ([`AssetLoader`](https://docs.rs/bevy/0.13.1/bevy/asset/trait.AssetLoader.html)s).

The error looks like this, where `bevy_asset::server` ends up not being able to find the asset loader.

```
Could not find an asset loader matching: Loader Name: None; Asset Type: None; Extension: None; Path: Some("uipackSpace_sheet.xml");
```

I am not currently sure if [load_untyped](https://github.com/bevyengine/bevy/blob/97f0555cb0674ed161be012100af3541b95a5877/crates/bevy_asset/src/server/mod.rs#L350) is supposed to work with [custom assets (bevy example)](https://github.com/bevyengine/bevy/blob/97f0555cb0674ed161be012100af3541b95a5877/examples/asset/custom_asset.rs). I have [asked in Discord](https://discord.com/channels/691052431525675048/1223713196460736555/1223713196460736555) to see if anyone knows.

`load_untyped` is used in `AssetCollection::load` as seen here. I've seen the issue with both loading_state and non-loading_state bevy_asset_loader examples.

<details><summary>example expanded macro</summary>

```rust
// Recursive expansion of AssetCollection macro
// =============================================

#[automatically_derived]
#[allow(unused_variables)]
impl AssetCollection for ImageAssets {
    fn create(
        world: &mut ::bevy::ecs::world::World,
    ) -> Self {
        let from_world_fields = ();
        world.resource_scope(|world,asset_keys: ::bevy::prelude::Mut< ::bevy_asset_loader::dynamic_asset::DynamicAssets> |{
            ImageAssets {
                space_sheet:{
                    let asset_server = world.get_resource:: < ::bevy::asset::AssetServer>().expect("Cannot get AssetServer");
                    asset_server.load("spaceShooter2_spritesheet_2X.xml")
                },
            }
        },)
    }
    fn load(
        world: &mut ::bevy::ecs::world::World,
    ) -> Vec<::bevy::prelude::UntypedHandle> {
        let cell = world.cell();
        let asset_server = cell
            .get_resource::<::bevy::prelude::AssetServer>()
            .expect("Cannot get AssetServer");
        let asset_keys = cell.get_resource:: <bevy_asset_loader::prelude::DynamicAssets>().expect("Cannot get bevy_asset_loader::prelude::DynamicAssets");
        let mut handles = vec![];
        handles.push(
            asset_server
                .load_untyped(
                    "spaceShooter2_spritesheet_2X.xml",
                )
                .untyped(),
        );
        handles
    }
}
```

</details>

**Comment by NiklasEi** [comment]
Thanks for opening an issue. I am aware of the problem and don't think this is supposed to work. Bevy needs to get the correct AssetLoader, but in this case, we don't give any possible "identification" to use for loader selection (AssetLoader in `.meta` file, registered extension or asset type).
You are [not the first user to stumble into this](https://discord.com/channels/691052431525675048/1062754025218510918/1221523889851728013), but I don't think I can easily fix this in `bevy_asset_loader` at the moment. The macro cannot know what initial asset type needs to be loaded since, in some cases, it will be different from the asset collection field type (e.g. a `StandardMaterial` needs to be loaded as an `Image` asset first).

**Comment by ChristopherBiscardi** [comment]
Feeling a bit silly on this one 😅 

`AssetLoader::extensions` must be a list of extensions *without* preceding dots. So `[".xml"]` fails with the above error while `["xml"]` succeeds.

It works for me now.

**Comment by NiklasEi** [comment]
I opened #208 to see if the plugin can support asset loaders without extensions.
