### ISSUE TITLE
Folder collection loading doesn't seem to work on Android

### ISSUE THREAD

**Issue by Selene-Amanita** [NiklasEi/bevy_asset_loader#213]
This feature: https://github.com/NiklasEi/bevy_asset_loader?tab=readme-ov-file#folders

The readme says it doesn't work on web builds, but it doesn't seem to work on android either, the resulting HashMap is empty.

It works as intended on PC and iPhone, and other assets (not loaded from folder) load on android.

Enumeration of file path ( https://github.com/NiklasEi/bevy_asset_loader?tab=readme-ov-file#list-of-paths ) works as intended on android too.

**Comment by NiklasEi** [comment]
Could you test with the vanilla Bevy `load_folder` please?

**Comment by Selene-Amanita** [comment]
I don't have a device readily available sorry but https://github.com/kgv/bevy_fluent/issues/43 suggests the vanilla Bevy load_folder doesn't work either. I think that should be reflected on `bevy_asset_loader`'s README?

**Comment by NiklasEi** [comment]
Android should work by now: https://github.com/bevyengine/bevy/pull/11495

I will add a note to the readme for missing web support.

**Comment by NiklasEi** [comment]
The readme actually already says "Loading folders is not supported for web builds. If you want to be compatible with Wasm, load you handles from a list of paths instead (see next section)." at the end of the folders section.
