### ISSUE TITLE
[Question] Loading assets with custom settings

### ISSUE THREAD

**Issue by Tam** [NiklasEi/bevy_asset_loader#215]
I'm loading in a repeating texture and have to load it with a custom `ImageSamplerDescriptor` to set the UV address mode.

```rust
fn(&mut ImageLoaderSettings) = move |s: &mut ImageLoaderSettings| {
    s.sampler = ImageSampler::Descriptor(ImageSamplerDescriptor {
        address_mode_u: ImageAddressMode::Repeat,
        address_mode_v: ImageAddressMode::Repeat,
        ..default()
    });
};
```
Is there a way to do this while loading the asset via asset loader?

**Comment by NiklasEi** [comment]
Not at the moment. You can only change the sampler to Linear or Nearest via derive macro attribute.

**Comment by rendaoer** [comment]
This is now implemented, but it seems that it can only be set for a single image, not for a folder.
