### ISSUE TITLE
allow deriving collections as arrays

### ISSUE THREAD

**Issue by bananaturtlesandwich** [NiklasEi/bevy_asset_loader#218]
as shown in this example in the readme
```rust
use bevy::prelude::*;
use bevy_asset_loader::asset_collection::AssetCollection;

#[derive(AssetCollection, Resource)]
struct MyAssets {
    #[asset(paths("images/player.png", "images/tree.png"), collection(typed))]
    files_typed: Vec<Handle<Image>>,
}
```
you can load collections as vectors but this can be a bit of a waste if you don't intend to mutate the resource (which i assume is the typical use case) so being able to do this as
```rust
use bevy::prelude::*;
use bevy_asset_loader::asset_collection::AssetCollection;

#[derive(AssetCollection, Resource)]
struct MyAssets {
    #[asset(paths("images/player.png", "images/tree.png"), collection(typed))]
    files_typed: [Handle<Image>; 2],
}
```
would be great but implementation would probably need a lot of work

**Comment by bananaturtlesandwich** [comment]
this can be done manually as well for now
impl AssetCollection for MyAssets {
    fn create(world: &mut World) -> Self {
        world.resource_scope(|world, _: Mut<DynamicAssets>| MyAssets {
            files_typed: {
                let asset_server = world
                    .get_resource::<AssetServer>()
                    .expect("Cannot get AssetServer");
                [
                    asset_server.load("images/player.png"),
                    asset_server.load("images/tree.png"),
                ]
            },
        })
    }

    fn load(world: &mut World) -> Vec<UntypedHandle> {
        let cell = world.cell();
        let asset_server = cell
            .get_resource::<::bevy::prelude::AssetServer>()
            .expect("Cannot get AssetServer");
        vec![
            asset_server
                .load_untyped("images/player.png")
                .untyped(),
                            asset_server
                .load_untyped("images/tree.png")
                .untyped(),
        ]
    }
}
```

**Comment by NiklasEi** [comment]
Does this have a real impact on performance or memory usage? Or do you see some other advantage of array over vec here?
The vector should have a fitting capacity since the number of entries is known.

**Comment by NiklasEi** [comment]
If there is no additional benefit of an array over Vec here, I would prefer to keep the code simple and not add support for arrays.
