### ISSUE TITLE
Already removed assets in code keeps trying to load it

### ISSUE THREAD

**Issue by Sirmadeira** [NiklasEi/bevy_asset_loader#220]
First of all lovely crate thank you for your work. Now to the issue.

So my app workflow goes as follows.

Load assets -> Go to main menu

The weird thing is . It is trying to load assets that I clearly expressed to remove. That is the only asset collection I have yet it gives me this error 

2024-06-29T17:24:32.979050Z ERROR bevy_asset::server: Path not found: /home/mori/Projects/psycho_project/assets/fonts/FiraSans-Bold.ttf

An asset that i told to remove any ideas on what might be the issue here? 

```
#[derive(AssetCollection, Resource)]
pub struct MyAssets {
    // Insert in this path which asset you want to load
    // He will be loaded with multiple handles and a usefull hashmap to identify it in our code
    #[asset(
        paths("skeleton.glb", "rigge_female.glb", "katana.glb"),
        collection(typed, mapped)
    )]
    pub gltf_files: HashMap<String, Handle<Gltf>>,
}
```

**Comment by NiklasEi** [comment]
You seem to have found a solution. Anything related to the plugin or something that could be improved?
