### ISSUE TITLE
Bevy_asset_loader doesn't work with bevy/asset_processor feature (0.14 Crates Release)

### ISSUE THREAD

**Issue by Braymatter** [NiklasEi/bevy_asset_loader#225]
Our game has several asset collections, and we use preprocessing to convert our textures to BASIS-LZ

Whenever we run our app with the preprocessing flag the AssetCollections never seem to get loaded, and we're stuck with a black screen. 

According to the logs, bevy_asset_loader is trying to load, but it looks like it somehow never completes. 

It just logs these repeated 'Check loading' logs in debug

![image](https://github.com/NiklasEi/bevy_asset_loader/assets/77391373/8dc9a043-5b4a-45a1-a934-cec01c28bd3e)

By contrast invoking the program without the pre-process flag does these 'check' logs for less than a second then loads normally. Both invocations appear to preprocess the assets correctly.

**Comment by NiklasEi** [comment]
The same worked in Bevy 0.13? Do you have a reproduction that I can access?

**Comment by Seldom-SE** [comment]
(I also work on this project)
> The same worked in Bevy 0.13?

Yes

**Comment by Braymatter** [comment]
Update from our side, bevy doesn't appear to be copying the .bin files from gltf's over to the ImportedAssets directory which is causing this issue. We've created an issue on bevy: https://github.com/bevyengine/bevy/issues/14190

Ideally we'd get an informative log or something from bevy_asset_loader, but the cause of this appears to be bevy. 

We're able to work around it by switching it to a .glb

**Comment by NiklasEi** [comment]
Good to know, thank you. Imo the warning should be coming from Bevy here.

**Comment by NiklasEi** [comment]
I don't think bevy_asset_loader should do anything here. If you disagree, feel free to open the issue again.
