### ISSUE TITLE
Check loading state with dependencies

### ISSUE THREAD

**Issue by NiklasEi** [NiklasEi/bevy_asset_loader#227]
A handle should only be counted as loaded by this plugin when all it's dependencies are loaded.

`count_loaded_handles` should be using https://docs.rs/bevy_asset/latest/bevy_asset/struct.AssetServer.html#method.is_loaded_with_dependencies

**Comment by mgi388** [comment]
@NiklasEi I briefly tested that out 1 line change locally, looks to be working 😌

**Comment by mgi388** [comment]
The `failure` variable also needs to account for deps too otherwise if a dep fails to load the loading screen infinitely shows rather than transitioning to the error state.
