### ISSUE TITLE
relativ path on itch.io

### ISSUE THREAD

**Issue by Rust-Ninja-Sabi** [NiklasEi/bevy_asset_loader#242]
Hello, I want to publish a bevy Programm on itch.io in wasm. I get 403 because it tries to load with an absolute path. What went wrong. Thanks. Sabi.

**Comment by NiklasEi** [comment]
You will have to make sure that all URLs that your game calls are relative. Pages like itch can host your game at path e.g. "itch.io/foobar/yourgame". Make sure that your asset requests go to "itch.io/foobar/yourgame/assets" and not "itch.io/assets". I have had this issue with the game's WASM file before. If you like examples, take a look at the web setup of https://github.com/NiklasEi/bevy_game_template (most notably [the relative public URL in the truck setup](https://github.com/NiklasEi/bevy_game_template/blob/46e7353adf77d671069593822488c19e02b6a24c/Trunk.toml#L2)).

**Comment by Rust-Ninja-Sabi** [comment]
Thanks Niklas. I will integrate it. Best regards sabi
