### ISSUE TITLE
Bevy 0.15 support

### ISSUE THREAD

**Issue by rendaoer** [NiklasEi/bevy_asset_loader#245]

**Comment by AlexAegis** [comment]
there's already a pr open, you can start using it from its branch:

```toml
bevy_asset_loader = { version = "0.22.0", git = "https://github.com/NiklasEi/bevy_asset_loader", branch = "bevy-0-15" }
```

**Comment by NiklasEi** [comment]
The branch above should work fine if you do not enable the `progress_tracking` feature. I will merge the PR and release the new version as soon as `iyes_progress` was updated.
