### ISSUE TITLE
Pull assets in FromWorld?

### ISSUE THREAD

**Issue by lecoqjacob** [NiklasEi/bevy_asset_loader#3]
Is it possible to pull the loaded assets/fonts when constructing FromWorld for structs?

```
struct MenuMaterials {
    background: Handle<ColorMaterial>,
    normal: Handle<ColorMaterial>,
    hovered: Handle<ColorMaterial>,
    pressed: Handle<ColorMaterial>,
    font: Handle<Font>,
    font_color: Color,
}

impl FromWorld for MenuMaterials {
    fn from_world(world: &mut World) -> Self {
        // access fonts here??
    }
}
```

**Comment by NiklasEi** [comment]
`AppBuilder::init_resource` will invoke `from_world` very early and not wait for any specific App state. So if you want to use `init_resource` it will not work.

But if you need the resources only after everything got loaded, you can add an `on_exit` exclusive system to the loading App state and insert your resources there. At that point, you are able to access the AssetCollections through the ECS world in `from_world`.

```rust
impl FromWorld for MenuMaterials {
    fn from_world(world: &mut World) -> Self {
        let fonts = world.get_resource::<FontAssets>().expect("Font assets not loaded");
        // use your loaded asset collection here
    }
}

fn prepare_resources(world: &mut World) {
    let menu_materials = MenuMaterials::from_world(world);
    world.insert_resource(menu_materials);
}
```

```rust
// register system on exit of loading app state
app.add_system_set(
        SystemSet::on_exit(AppState::Loading).with_system(prepare_resources.exclusive_system()),
)
```

**Comment by lecoqjacob** [comment]
Great stuff! Thank you

**Comment by NiklasEi** [comment]
FYI version 0.3.0 added build-in support for this pattern. You can now let the `AssetLoader` initialize your `FromWorld` resource for you.
```rust
    AssetLoader::new(MyStates::AssetLoading, MyStates::Next)
        .with_collection::<SpriteSheet>()
        .post_process::<MyTextureAtlas>()
        .build(&mut app);
```

See the `atlas_from_grid` example for the complete code.
