### ISSUE TITLE
Add Loading statistics

### ISSUE THREAD

**Issue by BrettWitty** [NiklasEi/bevy_asset_loader#6]
It would be handy to get some statistics from `AssetLoader` so while it's loading we can display some progress UI. It'd be on the programmer to put their systems in the right `State` and poll `AssetLoader` appropriately.

**Comment by NiklasEi** [comment]
Have you seen https://github.com/inodentry/bevy_loading?
I am currently working on integrating `bevy_loading`s progress tracking into `bevy_asset_loader`. That would make the asset loading compatible with other things you might want to track with your progress bar like connecting to game servers or generating terrain.
