### ISSUE TITLE
Race condition on multiple similar AssetLoaders

### ISSUE THREAD

**Issue by Kaendor** [NiklasEi/bevy_asset_loader#60]
Hello,

I am currently trying to apply clean asset loading to two of my `Plugin`.

As per the guide, I am initializing a loopless_state with `app.add_loopless_state(GameState::Loading)` before using any of my plugins.

I am doing the following : 

In MeteorPlugin :
```rust
AssetLoader::new(GameState::Loading)
            .continue_to_state(GameState::Level)
            .with_collection::<MeteorAssets>()
            .build(app);

app.add_enter_system(GameState::Level, spawn_asteroid_field);
```

In ShipPlugin : 
```rust
 AssetLoader::new(GameState::Loading)
            .continue_to_state(GameState::Level)
            .with_collection::<LoadingShipAssets>()
            .build(app);

app.add_enter_system(GameState::Level, setup_spaceship_system)
```

When I was using the AssetLoader in only one Plugin everything went fine. But as soon as I added asset collection loading to the other, I believe the `GameState::Level` was entered too soon and made my code panic since all the assets were not loaded yet.

It kinda looks like a race condition between each AssetLoader.

I thought when declaring more than one AssetLoader on a given state, it would aggregate all the collections needed, wait for all of them to load, and then transition to the given state.

Thank you for your time!

**Comment by NiklasEi** [comment]
Thank you for raising the issue. This should work, but I can reproduce, that it currently does not.

I'll fix it

**Comment by Kaendor** [comment]
Thanks a lot!
