### ISSUE TITLE
Version 0.11.0 on Crates.io provides a lib.rs without a prelude section.

### ISSUE THREAD

**Issue by Laocoon7** [NiklasEi/bevy_asset_loader#61]
I would expect crates.io to link to a version of bevy_asset_loader which includes the prelude. such as https://github.com/NiklasEi/bevy_asset_loader/blob/main/bevy_asset_loader/src/lib.rs

It is currently pointing to a version which looks like https://github.com/NiklasEi/bevy_asset_loader/blob/bevy_main/bevy_asset_loader/src/lib.rs

This breaks the examples when Cargo.toml includes bevy_asset_loader = "0.11.0" instead of pointing to the github repo.

**Comment by NiklasEi** [comment]
The latest release does not have a prelude. This is a new change on the `main` branch.

If you are using version `0.11.0`, you can [browse the examples on the corresponding tag](https://github.com/NiklasEi/bevy_asset_loader/tree/v0.11.0/bevy_asset_loader/examples).
