### ISSUE TITLE
Support TextureAtlas handles when deriving AssetCollection

### ISSUE THREAD

**Issue by NiklasEi** [NiklasEi/bevy_asset_loader#7]
```rust
#[derive(AssetCollection)]
struct MyAssets {
    #[asset(texture_atlas(cell_width = 100., cell_height = 96., columns = 8, rows = 1))]
    #[asset(path = "textures/female_adventurer.png")]
    female_adventurer: Handle<TextureAtlas>,
}
```

**Comment by LeonLiuY** [comment]
Hi, I can run the example `atlas_from_grid.rs` successfully in this repo. However when I do it in my project I get:
```
error[E0425]: cannot find value `atlases` in this scope
```
What could be wrong with my usage?

**Comment by NiklasEi** [comment]
You might have turned off the default features?

**Comment by LeonLiuY** [comment]
I don't know you mean which default features. 

I'm just using your template https://github.com/NiklasEi/bevy_game_template and change the TextureAssets to use TextureAtlas in `loading.rs` and it reports that error.

And there is `bevy = { version = "0.5.0", default-features = false }`, I tried enable default features it still has that error.

**Comment by NiklasEi** [comment]
Thank you, I can reproduce this issue and will look into it :)

**Comment by kirandesimone** [comment]
What was the fix for this issue? I'm currently having the same problem.

**Comment by NiklasEi** [comment]
From version `0.7` on the `render` feature is no longer a default feature. Did you enable it?

The original issue with the feature was a bug in the derive macro and has been fixed.

**Comment by kirandesimone** [comment]
ahh I see ok

This is my cargo.toml file


[features]
render = ["bevy_asset_loader/render"]


[dependencies]
bevy = "0.6.0"
bevy_asset_loader = "0.8.0"

**Comment by NiklasEi** [comment]
With that `Cargo.toml´ you will need to activate the `render` feature of your own crate. Is it working then?

**Comment by kirandesimone** [comment]
hmmm not sure I follow, sorry I've never used features before. I just tried to activate it with #[cfg(feature = "render")] but no luck and it inactivates the code??

`#[cfg(feature = "render")]
#[derive(AssetCollection)]
pub struct DungeonTileset {
    #[asset(texture_atlas(tile_size_x=16., tile_size_y=16., columns=16, rows=16))]
    #[asset(path="assets/DungeonTileset_v4.png")]
    sprite_sheet: Handle<TextureAtlas>
}`

I also tried putting over the mod but no cigar.

**Comment by kirandesimone** [comment]
AHHH I GOT IT. ok, thanks a ton for your help!
